### ISSUE TITLE
Compactibility for TYPO 3 11 LTS

### ISSUE THREAD

**Issue by Epoche-Napoleon** [slub/slub_zotero#8]
Hello,

is it planned to make the TYPO3 EXT:zotero also executable for TYPO3 11 LTS or will a new version be released with TYPO3 12 LTS?

**Comment by rbialoz** [comment]
I would be very much interested in a version working with  TYPO3 11 LTS.

**Comment by chrode** [comment]
Compatibility for TYPO 3 11 LTS hat been achieved with release 3.0.0
